version: '3.9'

services:
  lavalink:
      ports:
        - "2333:2333"
      volumes:
        - lava:/opt/Lavalink
      networks:
      - kongnet

volumes:
  lava:

networks:
  kongnet:
        attachable: true
        external: true