version: '3.9'

services:
  lavalink:
    image: lavalink:latest
    ports:
      - "2333:2333"
    volumes:
      - lava:/opt/Lavalink
    networks:
    - kongnet

networks:
  kongnet:
        attachable: true
        external: true

volumes:
  lava: